/****** SQL SCRIPT TO PREPARE THE STAGING TABLE *******/

/****** YOU CAN RUN THIS SCRIPT AT ONCE!!! *******/

--- COMBINE ALL 17 RAW TABLES INTO ONE BIG TABLE ---

USE water_quality;

DROP TABLE IF EXISTS dw_water_quality;
GO

SELECT * INTO dw_water_quality FROM _2000;

INSERT INTO dw_water_quality
	SELECT * FROM _2001
		UNION
	SELECT * FROM _2002
		UNION
	SELECT * FROM _2003
		UNION
	SELECT * FROM _2004
		UNION
	SELECT * FROM _2005
		UNION
	SELECT * FROM _2006
		UNION
	SELECT * FROM _2007
		UNION
	SELECT * FROM _2008
		UNION
	SELECT * FROM _2009
		UNION
	SELECT * FROM _2010
		UNION
	SELECT * FROM _2011
		UNION
	SELECT * FROM _2012
		UNION
	SELECT * FROM _2013
		UNION
	SELECT * FROM _2014
		UNION
	SELECT * FROM _2015
		UNION
	SELECT * FROM _2016;



/****** END OF SCRIPT *******//****** END OF SCRIPT *******/
